# Generated by Django 2.1.7 on 2019-06-30 21:42

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import scan.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Only letters and spaces are allowed.', regex='^[a-zA-Z ]+$')])),
                ('last_name', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Only letters and spaces are allowed.', regex='^[a-zA-Z ]+$')])),
                ('birth_date', models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(1900, 1, 1)), django.core.validators.MaxValueValidator(datetime.date(2019, 6, 30))])),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6)),
                ('Chemo', models.BooleanField(blank=True, null=True)),
                ('Last_Chemo', models.DateField(blank=True, null=True)),
                ('smoker', models.BooleanField(blank=True, null=True)),
                ('Packs_yearly', models.FloatField(blank=True, null=True)),
                ('diabetes', models.BooleanField(blank=True, null=True)),
                ('insulin', models.BooleanField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(500)])),
            ],
        ),
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('diag_date', models.DateField(default=datetime.date(2019, 6, 30))),
                ('diagnosis', models.CharField(max_length=200)),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('scan', models.ImageField(upload_to=scan.models.user_directory_path, validators=[scan.models.validate_size])),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scan.Patient')),
            ],
        ),
    ]
