# Generated by Django 2.1.7 on 2019-02-13 21:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('dia_id', models.AutoField(primary_key=True, serialize=False)),
                ('diagnosis', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('birth_date', models.DateField()),
                ('gender', models.IntegerField(choices=[(1, 'Male'), (2, 'Female')])),
                ('age', models.IntegerField()),
                ('Chemo', models.BooleanField()),
                ('Last_Chemo', models.DateField()),
                ('smoker', models.BooleanField()),
                ('Packs_yearly', models.IntegerField()),
                ('diabetes', models.BooleanField()),
                ('insulin', models.BooleanField()),
                ('weight', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('dia_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scan.Diagnosis')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scan.Patient')),
            ],
        ),
    ]
