# Generated by Django 2.1.7 on 2019-02-26 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scan', '0004_auto_20190219_1827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scan',
            name='doctor',
        ),
        migrations.AddField(
            model_name='scan',
            name='diag_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scan',
            name='reason',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='scan',
            name='diagnosis',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='Diagnosis',
        ),
    ]
