# Generated by Django 2.1.7 on 2019-03-04 16:58

from django.db import migrations, models
import scan.models


class Migration(migrations.Migration):

    dependencies = [
        ('scan', '0005_auto_20190226_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='file',
            field=models.ImageField(default=1, upload_to=scan.models.user_directory_path),
            preserve_default=False,
        ),
    ]
