# Generated by Django 2.1.7 on 2019-03-11 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scan', '0007_auto_20190304_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=20),
        ),
    ]
