# Generated by Django 2.1.7 on 2019-03-14 15:19

from django.db import migrations, models
import scan.models


class Migration(migrations.Migration):

    dependencies = [
        ('scan', '0009_scan_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='file',
            field=models.ImageField(upload_to=scan.models.user_directory_path, validators=[scan.models.validate_size]),
        ),
    ]
