# Generated by Django 2.1.7 on 2019-03-04 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctoruser',
            name='email',
            field=models.EmailField(blank=True, error_messages={'unique': 'Email already exists.'}, max_length=254, unique=True),
        ),
    ]
